import dotenv from 'dotenv';
import path from 'path';

// Load env files in priority order — user secrets last so they override non-secret values
dotenv.config({ path: path.resolve(process.cwd(), '.env') });
dotenv.config({ path: path.resolve(process.cwd(), 'env/.env.dev.user') });

function splitCsvLower(value: string | undefined): string[] {
    return (value || '').split(',').map(s => s.trim().toLowerCase()).filter(Boolean);
}

const DEFAULT_SENSITIVE_TOPICS = [
    // Compensation
    'sweldo', 'sahod', 'salary', 'compensation', 'pay grade', 'pay rate', 'salary ng',
    // Pricing / costs
    'pricing', 'presyo', 'cost structure', 'markup', 'margin', 'internal price',
    // Employee personal data
    'personal data', 'personal info', 'employee record', 'sss number', 'health record',
    'medical info', 'home address',
    // Credentials / secrets
    'api key', 'secret key', 'access key', 'client secret', 'database password', 'credentials ng',
    // Unannounced / legal
    'unannounced', 'merger', 'acquisition', 'layoff', 'restructuring', 'confidential project'
];

export const config = {
    companyName: process.env.COMPANY_NAME || 'Amertron Corporation',
    port: parseInt(process.env.PORT || '3979', 10),
    nodeEnv: process.env.NODE_ENV || 'development',

    // ── Nextcloud Talk bot settings ────────────────────────────────────────────
    // Base URL of the Nextcloud server (no trailing slash), e.g. https://amertron-nextcloud-test.dedyn.io
    talkServerUrl: (process.env.TALK_SERVER_URL || '').replace(/\/+$/, ''),
    // Shared secret generated by `occ talk:bot:install` — used to verify inbound
    // webhook signatures and to sign outbound replies.
    talkSecret: process.env.TALK_SECRET || process.env.SECRET_TALK_SECRET || '',
    talkWebhookPath: process.env.TALK_WEBHOOK_PATH || '/api/talk/webhook',
    // When true (recommended), Ami only answers messages that mention her by
    // name — the word "ami" anywhere in the text (e.g. "ami help", "hello ami").
    // When false she answers every regular chat message in approved rooms.
    talkRequireMention: (process.env.TALK_REQUIRE_MENTION || 'true') === 'true',
    // Optional Nextcloud user used to download shared images over WebDAV when
    // the webhook carries no public share link. Must be a member of the room.
    talkAdminUser: process.env.TALK_ADMIN_USER || '',
    talkAdminPassword: process.env.SECRET_TALK_ADMIN_PASSWORD || '',
    // Numeric bot id printed by `occ talk:bot:install`; used to auto-enable
    // Ami in notification rooms added via $notify-add.
    talkBotId: process.env.TALK_BOT_ID || '1',

    // Hourly nudge: Ami reminds approved rooms how to reach her. Set
    // TALK_NUDGE_INTERVAL_MIN=0 to disable. The reminder text is TALK_NUDGE_MESSAGE.
    // Notification rooms (added via $notify-add) are skipped automatically.
    talkNudgeIntervalMin: parseInt(process.env.TALK_NUDGE_INTERVAL_MIN || '60', 10) || 0,
    talkNudgeMessage: process.env.TALK_NUDGE_MESSAGE ||
        '💡 Need IT help or want to report an issue? Just type **ami** in this chat (e.g. "ami assist" or "ami help") and I\'ll jump in.',

    // ── AI provider selection ──────────────────────────────────────────────────
    aiProvider: (process.env.AI_PROVIDER || 'auto') as 'gemini' | 'openai' | 'azure' | 'auto',

    geminiApiKey: process.env.GEMINI_API_KEY || process.env.SECRET_GEMINI_API_KEY || '',
    geminiModelName: process.env.GEMINI_MODEL_NAME || 'gemini-3.5-flash-lite',

    azureOpenAIEndpoint: process.env.AZURE_OPENAI_ENDPOINT || '',
    azureOpenAIKey: process.env.AZURE_OPENAI_KEY || process.env.SECRET_AZURE_OPENAI_KEY || '',
    azureOpenAIDeployment: process.env.AZURE_OPENAI_DEPLOYMENT || '',

    openAIApiKey: process.env.OPENAI_API_KEY || process.env.SECRET_OPENAI_API_KEY || '',
    openAIModel: process.env.OPENAI_MODEL || 'gpt-4o',

    // ── Personality / safety ───────────────────────────────────────────────────
    sensitiveTopics: [
        ...DEFAULT_SENSITIVE_TOPICS,
        ...splitCsvLower(process.env.SENSITIVE_TOPICS)
    ],

    // ── Conversation tuning ───────────────────────────────────────────────────
    rateLimitWindow: parseInt(process.env.RATE_LIMIT_WINDOW || '60000', 10),
    maxRequestsPerWindow: parseInt(process.env.MAX_REQUESTS_PER_WINDOW || '10', 10),
    sessionTimeout: parseInt(process.env.SESSION_TIMEOUT || '120000', 10),
    maxHistoryTurns: parseInt(process.env.MAX_HISTORY_TURNS || '20', 10),

    // ── Image handling ─────────────────────────────────────────────────────────
    maxImageSizeMB: parseInt(process.env.MAX_IMAGE_SIZE_MB || '10', 10)
};
